[tool.poetry]
name = "multi-animal-tracker"
version = "0.1.0"
description = "A multi-animal tracking system using computer vision and deep learning."
authors = ["Rishika Mohanta <rishika.mohanta@example.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/neurorishika/multi-animal-tracker"
repository = "https://github.com/neurorishika/multi-animal-tracker"
keywords = ["animal tracking", "computer vision", "deep learning"]

[tool.poetry.dependencies]
python = "^3.8"
opencv-python = "^4.5.3"
tensorflow = "^2.6.0"
numpy = "^1.21.2"
pandas = "^1.3.3"
scikit-learn = "^0.24.2"
matplotlib = "^3.4.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.7b0"
isort = "^5.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"